### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by jciupis** [srubenacker/DeepDog#1]
Hi!

I appreciate the work you put in this project. I'm also starting some deep learning with the Stanford dogs database and I was wondering if I could reuse some of the image preparation code you wrote. There is no license in this repo though, and it seems that [nobody has the permission to use this code then](https://choosealicense.com/no-permission/). That's why I'm creating this issue - would you consider adding a license to the repo so that your code could be reused? If it's not an option, please respond in this issue.

**Comment by srubenacker** [comment]
I've added a license.  Cheers.
